const samples={program:["using System.Windows.Forms;","","namespace NovaCrypto;","","public static class Program","{","    [STAThread]","    public static int Main(string[] args)","    {","        ApplicationConfiguration.Initialize();","        Application.Run(new GitMainForm());","        return 0;","    }","}"],form:["public sealed class GitMainForm : Form","{","    readonly RichTextBox _details = new();","","    void SetDetails(string text)","    {","        _details.Text = text;","        HighlightSyntax();","    }","","    async Task ShowSelectedDiff()","    {","        var diff = await _git.Run(_root, \"diff\", \"HEAD\");","        SetDetails(diff.StandardOutput);","    }","}"],readme:["# NovaGit","","A clear, modern Git desktop client for Windows.","","## Features","","- Browse source files","- Review Git diffs","- Connect remotes","- Inspect commits and objects"]};
const code=document.querySelector('#code-lines'),tabs=[...document.querySelectorAll('.file-tab')],title=document.querySelector('#file-title');
function escape(s){return s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function highlight(line){let x=escape(line);if(x.startsWith('+'))return `<span class="diff-add">${x}</span>`;if(x.startsWith('-'))return `<span class="diff-remove">${x}</span>`;x=x.replace(/(\/\/.*)/g,'<span class="comment">$1</span>');x=x.replace(/(&quot;.*?&quot;)/g,'<span class="string">$1</span>');x=x.replace(/\b(public|static|class|using|namespace|async|await|return|new|void)\b/g,'<span class="key">$1</span>');x=x.replace(/\b(Program|GitMainForm|RichTextBox|Task)\b/g,'<span class="type">$1</span>');return x}
function render(name){code.innerHTML=samples[name].map(line=>`<li>${highlight(line)||' '}</li>`).join('');title.textContent=name==='program'?'Program.cs':name==='form'?'GitMainForm.cs':'README.md'}render('program');
tabs.forEach(tab=>tab.addEventListener('click',()=>{tabs.forEach(x=>x.classList.remove('active'));tab.classList.add('active');render(tab.dataset.file);document.querySelector('#changes-panel').classList.add('hidden');document.querySelector('#commits-panel').classList.add('hidden');document.querySelector('#code-panel').classList.remove('hidden');document.querySelector('#view-label').textContent='Files'}));
document.querySelectorAll('.side-item[data-panel]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.side-item').forEach(x=>x.classList.remove('active'));button.classList.add('active');const panel=button.dataset.panel;document.querySelector('#view-label').textContent=panel[0].toUpperCase()+panel.slice(1);document.querySelector('#code-panel').classList.toggle('hidden',panel!=='files');document.querySelector('#changes-panel').classList.toggle('hidden',panel!=='changes');document.querySelector('#commits-panel').classList.toggle('hidden',panel!=='commits');title.textContent=panel==='files'?'Program.cs':panel==='changes'?'Working tree':'Recent commits'}));
document.querySelectorAll('[data-diff]').forEach(button=>button.addEventListener('click',()=>{const kind=button.dataset.diff;code.innerHTML=[`diff --git a/${kind==='form'?'GitMainForm.cs':'GitCli.cs'} b/${kind==='form'?'GitMainForm.cs':'GitCli.cs'}`,"@@ -8,3 +8,5 @@",kind==='form'?'-        _details.Text = text;': '-        return process.ExitCode;',kind==='form'?'+        SetDetails(text);': '+        Console.Write(await stdout);',kind==='form'?'+        HighlightSyntax();': '+        return process.ExitCode;'].map(x=>`<li>${highlight(x)}</li>`).join('');document.querySelector('#changes-panel').classList.add('hidden');document.querySelector('#code-panel').classList.remove('hidden');title.textContent='Diff preview'}));
document.querySelector('#theme-toggle').addEventListener('click',()=>document.body.classList.toggle('dark'));document.querySelector('#copy-button').addEventListener('click',async()=>{await navigator.clipboard?.writeText(samples.program.join('\n'));const toast=document.querySelector('#toast');toast.classList.add('visible');setTimeout(()=>toast.classList.remove('visible'),1800)});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.14});document.querySelectorAll('.reveal').forEach(element=>observer.observe(element));
